### ISSUE TITLE
tessdata里的数据是否需要单独手动生成

### ISSUE THREAD

**Issue by d4wner** [fupinglee/CrackCaptcahLogin#1]
按照您的流程指导做了以后，发现会出现下面的错误。
```
Error opening data file ./tessdata/num.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'num'
Tesseract couldn't load any languages!
```
我在软件界面已经填好了验证码的url，不知道这里的数据是否会自动生成。
还有就是TESSDATA_PREFIX 这个是要设置环境变量的值？
您的说明里没有提到，我这边是不是要设置为tessdata的所在的目录？

**Comment by d4wner** [comment]
PS:前面我指的是训练识别验证码的库是否需要单独手动生成，我知道次世代之类需要自己用单独的软件训练库，但不知道这个tesseract是不是也是这样。

**Comment by fupinglee** [comment]
可以参考[在jar同级目录下创建文件夹](https://github.com/fupinglee/CrackCaptcahLogin#3在jar同级目录下创建文件夹)
直接用[我的识别库](https://github.com/fupinglee/CrackCaptcahLogin/tree/master/tessdata)或者复制你安装目录里面Tesseract-OCR\tessdata中的识别库。

我这个识别库只是针对我自己这里的验证码适用。
例如验证码

![验证码](https://github.com/fupinglee/CrackCaptcahLogin/blob/master/tmp/yzm2.jpg)

**Comment by d4wner** [comment]
您说的就是把eng.traineddata等识别库文件，扔新建的tessdata文件夹里就行吧？，另外我想训练其他识别库需要找啥软件呢？还是只能找打码平台？

**Comment by fupinglee** [comment]
打码平台是直接识别验证码了。要想自己识别，可以自己写识别的方法，不一定都会用到Tesseract的。训练识别库的话可以使用jTessBoxEditorFX这个工具

**Comment by d4wner** [comment]
我先看看，非常感谢~
